ConfigVersion: 1

DataStore:
  #Available types are H2, MySQL and SQLite
  Type: H2
  MySQL:
    Location: "localhost"
    Port: 5503
    Username: "admin"
    Password: "Password"
    Database: "Spigot"
Permissions:
  lapislogin,player:
    Required: 2
    Admin: 0
  lapislogin,vip:
    Required: 0
    Admin: 0
  lapislogin,admin:
    Required: 1
    Admin: 1