ConfigVersion: 1

DataStore:
  #Available types are H2, MySQL and SQLite
  Type: H2
  MySQL:
    Location: "localhost"
    Port: 5503
    Username: "admin"
    Password: "Password"
    Database: "Spigot"