name: LapisLogin
version: ${project.version}
main: net.lapismc.lapislogin.LapisLogin
authors: [Dart2112]
description: Simple login plugin for offline mode servers
commands:
  login:
    description: Allows you to login to the server
  register:
    description: Allows you to register a password for future logins
